//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalAccount
    {
        public int ExternalProviderId { get; set; }
        public string UserIdentity { get; set; }
        public int ProfileId { get; set; }
    
        public virtual ExternalProvider ExternalProvider { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
