//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.Comments = new HashSet<Comment>();
            this.MovieLocalizations = new HashSet<MovieLocalization>();
            this.Ratings = new HashSet<Rating>();
            this.Seances = new HashSet<Seance>();
            this.Actors = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public int Length { get; set; }
        public Nullable<int> GenreId { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public Nullable<int> DirectorId { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<int> PhotoId { get; set; }
        public string VideoLink { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> RemoveExecutorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieLocalization> MovieLocalizations { get; set; }
        public virtual Person Director { get; set; }
        public virtual Photo Photo { get; set; }
        public virtual Profile Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seance> Seances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Actors { get; set; }
    }
}
