//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketPreOrdersDeleted
    {
        public int Id { get; set; }
        public int Row { get; set; }
        public int Place { get; set; }
        public int SeanceId { get; set; }
        public System.DateTime DateTime { get; set; }
        public int ProfileId { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Seance Seance { get; set; }
    }
}
